name: Run Cron Job

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (UTC time)

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API
        run: curl -X GET https://leap-backend.vercel.app/api/order/check-expiry